#!/bin/bash

RESPONSE=("Sure thing!" "No problem!" "Absolutely!" "Right away!")

if [[ $@ == '' ]] ; then
	echo "What can I do for you?"
	read CMD
	echo "${RESPONSE[$RANDOM%${#RESPONSE[@]}]}"
	exec $CMD
else
	echo "${RESPONSE[$RANDOM%${#RESPONSE[@]}]}"
	exec $@
fi
